### ISSUE TITLE
tarea infografia

### ISSUE THREAD

**Issue by Felix-Angel** [SistemasTecTlaxiaco/infografia-FelixAngel79#3]
[INFOGRAFIA_FELIX._SISTEMAS.NUMERICOS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-FelixAngel79/files/12555703/INFOGRAFIA_FELIX._SISTEMAS.NUMERICOS.pdf)

**Comment by 23620031** [comment]
REDACCIÓN Y ORTOGRAFÍA 10/10
EXPOSICIÓN DE IDEAS CENTRALES 15/15
ORGANIZACIÓN DE LA INFORMACIÓN 15/15
USO DE IMÁGENES Y COLORES 15/15
PRESENTACIÓN VISUAL 15/15
REFERENCIAS 15/15
PRESENTACIÓN 15/15

CALIFICADO POR EL EQUIPO DE "LÓPEZ DOMÍNGUEZ ISAÍAS BRAYAN"

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
